 export const product2=[
  {
    id: "1",
    Title: "Google Pixel 7 (Obsidian, 128 GB)",
    Name: "Google Pixel 7 (Obsidian, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/u/3/-original-imaggsuddwubypxp.jpeg?q=70&crop=false",
    Actualprice: "59,999",
    Price: "33,999",
    Rating: "4.3",
    Discount: "43",
    Availableoffer: "Available offersBank Offer₹2000 Off On ICICI Bank Credit Card TransactionsT&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹26000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹5,667/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "16,928 Ratings"
  },
  {
    id: "2",
    Title: "Google Pixel 9 Pro (Obsidian, 256 GB)",
    Name: "Google Pixel 9 Pro (Obsidian, 256 GB)  (16 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/m/p/j/-original-imah5mtpdzrutn3c.jpeg?q=70&crop=false",
    Actualprice: "",
    Price: "1,09,999",
    Rating: "4.6",
    Discount: "",
    Availableoffer: "Available offersBank Offer₹10000 Off On Selected Bank Credit Card Transactions.T&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CNo cost EMI ₹18,334/month. Standard EMI also availableView Plans",
    Numberofrating: "100 Ratings"
  },
  {
    id: "3",
    Title: "Google Pixel 7a (Snow, 128 GB)",
    Name: "Google Pixel 7a (Snow, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/v/f/d/-original-imagpgx4g2m63gfh.jpeg?q=70&crop=false",
    Actualprice: "43,999",
    Price: "30,999",
    Rating: "4.1",
    Discount: "29",
    Availableoffer: "Available offersBank Offer₹2000 Off On ICICI Bank Credit Card TransactionsT&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹12999 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹5,167/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "23,161 Ratings"
  },
  {
    id: "4",
    Title: "Google Pixel 8 (Hazel, 256 GB)",
    Name: "Google Pixel 8 (Hazel, 256 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/y/x/-original-imagtwh5zrcy9hfj.jpeg?q=70&crop=false",
    Actualprice: "82,999",
    Price: "47,999",
    Rating: "4.4",
    Discount: "42",
    Availableoffer: "Available offersBank Offer₹2000 Off On ICICI Bank Credit Card TransactionsT&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹35000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹8,000/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "14,112 Ratings"
  },
  {
    id: "5",
    Title: "Google Pixel 8a (Aloe, 128 GB)",
    Name: "Google Pixel 8a (Aloe, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/p/t/-original-imahyzygjdzrjgfh.jpeg?q=70&crop=false",
    Actualprice: "52,999",
    Price: "43,999",
    Rating: "4.2",
    Discount: "16",
    Availableoffer: "Available offersBank Offer₹2000 Off On ICICI Bank Credit Card TransactionsT&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹9000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹7,334/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "1,392 Ratings"
  },
  {
    id: "6",
    Title: "Google Pixel 7a (Charcoal, 128 GB)",
    Name: "Google Pixel 7a (Charcoal, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/n/i/d/-original-imagpgx4erjqnpzx.jpeg?q=70&crop=false",
    Actualprice: "43,999",
    Price: "30,999",
    Rating: "4.1",
    Discount: "29",
    Availableoffer: "Available offersBank Offer₹2000 Off On ICICI Bank Credit Card TransactionsT&CBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹12999 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹5,167/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "23,161 Ratings"
  },
  {
    id: "7",
    Title: "REDMI 13C (Stardust Black, 128 GB)",
    Name: "REDMI 13C (Stardust Black, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/v/e/a/-original-imahfk4xuk7ntphs.jpeg?q=70&crop=false",
    Actualprice: "11,999",
    Price: "7,199",
    Rating: "4.3",
    Discount: "40",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹1100 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with MobileT&CEMI starting from ₹254/monthView Plans",
    Numberofrating: "67,628 Ratings"
  },
  {
    id: "8",
    Title: "REDMI 13 5G (Hawaiian Blue, 128 GB)",
    Name: "REDMI 13 5G (Hawaiian Blue, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/s/o/-original-imah4smtz8yqfbd9.jpeg?q=70&crop=false",
    Actualprice: "17,999",
    Price: "12,999",
    Rating: "4.2",
    Discount: "27",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹500 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹2,167/month. Standard EMI also availableView Plans",
    Numberofrating: "12,182 Ratings"
  },
  {
    id: "9",
    Title: "REDMI 13C 5G (Starlight Black, 128 GB)",
    Name: "REDMI 13C 5G (Starlight Black, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/q/5/-original-imahfkf6jcuhhzyb.jpeg?q=70&crop=false",
    Actualprice: "13,999",
    Price: "8,999",
    Rating: "4.3",
    Discount: "35",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹5000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with MobileT&CEMI starting from ₹317/monthView Plans",
    Numberofrating: "29,641 Ratings"
  },
  {
    id: "10",
    Title: "REDMI 13C (Starfrost White, 128 GB)",
    Name: "REDMI 13C (Starfrost White, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/t/f/a/-original-imahfk4xp4xcggyt.jpeg?q=70&crop=false",
    Actualprice: "11,999",
    Price: "7,199",
    Rating: "4.3",
    Discount: "40",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4800 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with MobileT&CEMI starting from ₹254/monthView Plans",
    Numberofrating: "67,628 Ratings"
  },
  {
    id: "11",
    Title: "REDMI 13C 5G (Startrail Silver, 128 GB)",
    Name: "REDMI 13C 5G (Startrail Silver, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/d/f/0/-original-imahfkf6uyxnvmcy.jpeg?q=70&crop=false",
    Actualprice: "15,999",
    Price: "10,999",
    Rating: "4.2",
    Discount: "31",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹750 Off On All Banks Credit Card Transactions.T&CSpecial PriceGet extra ₹5000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹1,834/month. Standard EMI also availableView PlansView 1 more offer",
    Numberofrating: "18,235 Ratings"
  },
  {
    id: "12",
    Title: "REDMI 13C 5G (Starlight Black, 128 GB)",
    Name: "REDMI 13C 5G (Starlight Black, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/q/5/-original-imahfkf6jcuhhzyb.jpeg?q=70&crop=false",
    Actualprice: "15,999",
    Price: "10,999",
    Rating: "4.2",
    Discount: "31",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹750 Off On All Banks Credit Card Transactions.T&CSpecial PriceGet extra ₹5000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹1,834/month. Standard EMI also availableView PlansView 1 more offer",
    Numberofrating: "18,235 Ratings"
  },
  {
    id: "13",
    Title: "SAMSUNG Galaxy A14 5G (Black, 128 GB)",
    Name: "SAMSUNG Galaxy A14 5G (Black, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/2/o/-original-imah4sss2hjckcdk.jpeg?q=70&crop=false",
    Actualprice: "15,499",
    Price: "9,999",
    Rating: "4.2",
    Discount: "35",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹5500 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - Samsung1T&CEMI starting from ₹352/monthView Plans",
    Numberofrating: "29,309 Ratings"
  },
  {
    id: "14",
    Title: "SAMSUNG Galaxy M35 5G (Moonlight Blue, 128 GB)",
    Name: "SAMSUNG Galaxy M35 5G (Moonlight Blue, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/n/u/5/galaxy-m35-5g-sm-m356b-samsung-original-imah5qgyszh7ygft.jpeg?q=70&crop=false",
    Actualprice: "24,499",
    Price: "16,225",
    Rating: "4.4",
    Discount: "33",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on BOBCARD Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CSpecial PriceGet extra ₹3660 off (price inclusive of cashback/coupon)T&CView 4 more offers",
    Numberofrating: "2,323 Ratings"
  },
  {
    id: "15",
    Title: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)",
    Name: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/2/y/c/-original-imah4sssdf9pgz3e.jpeg?q=70&crop=false",
    Actualprice: "20,999",
    Price: "10,999",
    Rating: "4.2",
    Discount: "47",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹10000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - Samsung1T&CEMI starting from ₹387/monthView Plans",
    Numberofrating: "46,736 Ratings"
  },
  {
    id: "16",
    Title: "SAMSUNG Galaxy A14 5G (Light Green, 128 GB)",
    Name: "SAMSUNG Galaxy A14 5G (Light Green, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/e/g/-original-imah4sssfvvahchb.jpeg?q=70&crop=false",
    Actualprice: "15,499",
    Price: "9,999",
    Rating: "4.2",
    Discount: "35",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹5500 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - Samsung1T&CEMI starting from ₹352/monthView Plans",
    Numberofrating: "29,309 Ratings"
  },
  {
    id: "17",
    Title: "SAMSUNG Galaxy F05 (Twilight Blue, 64 GB)",
    Name: "SAMSUNG Galaxy F05 (Twilight Blue, 64 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/r/f/-original-imah56hkgehywn5b.jpeg?q=70&crop=false",
    Actualprice: "9,999",
    Price: "7,999",
    Rating: "4.2",
    Discount: "20",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CExtra 10% off on Combo with Mobile - Samsung3T&CEMI starting from ₹282/monthView Plans",
    Numberofrating: "13,345 Ratings"
  },
  {
    id: "18",
    Title: "SAMSUNG Galaxy A14 5G (Black, 128 GB)",
    Name: "SAMSUNG Galaxy A14 5G (Black, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/y/2/o/-original-imah4sss2hjckcdk.jpeg?q=70&crop=false",
    Actualprice: "20,999",
    Price: "10,999",
    Rating: "4.2",
    Discount: "47",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹10000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - Samsung1T&CEMI starting from ₹387/monthView Plans",
    Numberofrating: "46,736 Ratings"
  },
  {
    id: "19",
    Title: "Apple iPhone 14 (Midnight, 128 GB)",
    Name: "Apple iPhone 14 (Midnight, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/9/e/e/-original-imaghx9q5rvcdghy.jpeg?q=70&crop=false",
    Actualprice: "59,900",
    Price: "50,999",
    Rating: "4.6",
    Discount: "14",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹8901 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - Google,Nothing,AppleT&CExtra 15% off on ComboT&CView 1 more offer",
    Numberofrating: "3,07,427 Ratings"
  },
  {
    id: "20",
    Title: "Apple iPhone 15 Pro (Natural Titanium, 128 GB)",
    Name: "Apple iPhone 15 Pro (Natural Titanium, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/9/u/a/-original-imagtc4hsx9mzfra.jpeg?q=70&crop=false",
    Actualprice: "1,34,900",
    Price: "1,03,999",
    Rating: "4.6",
    Discount: "22",
    Availableoffer: "Sold OutThis item is currently out of stock",
    Numberofrating: "2,590 Ratings"
  },
  {
    id: "21",
    Title: "Apple iPhone 15 Plus (Blue, 128 GB)",
    Name: "Apple iPhone 15 Plus (Blue, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70&crop=false",
    Actualprice: "79,900",
    Price: "67,999",
    Rating: "4.6",
    Discount: "14",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹2,500 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹50,000T&CBank OfferFlat ₹3,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹50,000T&CSpecial PriceGet extra ₹11901 off (price inclusive of cashback/coupon)T&CView 4 more offers",
    Numberofrating: "31,733 Ratings"
  },
  {
    id: "22",
    Title: "Apple iPhone 15 (Pink, 128 GB)",
    Name: "Apple iPhone 15 (Pink, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/c/k/-original-imagtc5fuzkvczr7.jpeg?q=70&crop=false",
    Actualprice: "69,900",
    Price: "58,999",
    Rating: "4.6",
    Discount: "15",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹2,500 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹50,000T&CBank OfferFlat ₹3,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹50,000T&CSpecial PriceGet extra ₹10901 off (price inclusive of cashback/coupon)T&CView 3 more offers",
    Numberofrating: "2,07,248 Ratings"
  },
  {
    id: "23",
    Title: "Apple iPhone 15 (Blue, 128 GB)",
    Name: "Apple iPhone 15 (Blue, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70&crop=false",
    Actualprice: "69,900",
    Price: "58,999",
    Rating: "4.6",
    Discount: "15",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹2,500 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹50,000T&CBank OfferFlat ₹3,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹50,000T&CSpecial PriceGet extra ₹10901 off (price inclusive of cashback/coupon)T&CView 3 more offers",
    Numberofrating: "2,07,248 Ratings"
  },
  {
    id: "24",
    Title: "Apple iPhone 15 (Black, 128 GB)",
    Name: "Apple iPhone 15 (Black, 128 GB)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/d/9/-original-imagtc2qzgnnuhxh.jpeg?q=70&crop=false",
    Actualprice: "69,900",
    Price: "58,999",
    Rating: "4.6",
    Discount: "15",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹2,500 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹50,000T&CBank OfferFlat ₹3,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹50,000T&CSpecial PriceGet extra ₹10901 off (price inclusive of cashback/coupon)T&CView 3 more offers",
    Numberofrating: "2,07,248 Ratings"
  },
  {
    id: "25",
    Title: "realme 12 Pro+ 5G (Explorer Red, 256 GB)",
    Name: "realme 12 Pro+ 5G (Explorer Red, 256 GB)  (12 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/v/c/12-pro-5g-rmx3840-realme-original-imagxgnkafjjhpmk.jpeg?q=70&crop=false",
    Actualprice: "37,999",
    Price: "26,999",
    Rating: "4.5",
    Discount: "28",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹1,200 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹15,000T&CBank OfferFlat ₹1,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹15,000T&CSpecial PriceGet extra ₹11000 off (price inclusive of cashback/coupon)T&CView 10 more offers",
    Numberofrating: "9,911 Ratings"
  },
  {
    id: "26",
    Title: "realme 12 Pro+ 5G (Submarine Blue, 256 GB)",
    Name: "realme 12 Pro+ 5G (Submarine Blue, 256 GB)  (12 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/t/u/-original-imagxhd5xtjuwnqz.jpeg?q=70&crop=false",
    Actualprice: "37,999",
    Price: "26,999",
    Rating: "4.5",
    Discount: "28",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹11000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹9,000/month. Standard EMI also availableView PlansExtra 10% off on Combo with MobileT&C",
    Numberofrating: "9,911 Ratings"
  },
  {
    id: "27",
    Title: "realme P1 Pro 5G (Parrot Blue, 128 GB)",
    Name: "realme P1 Pro 5G (Parrot Blue, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/4/y/b/-original-imahyzygycuyg3mq.jpeg?q=70&crop=false",
    Actualprice: "24,999",
    Price: "19,999",
    Rating: "4.4",
    Discount: "20",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹1,200 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹15,000T&CBank OfferFlat ₹1,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹15,000T&CSpecial PriceGet extra ₹5000 off (price inclusive of cashback/coupon)T&CView 10 more offers",
    Numberofrating: "22,812 Ratings"
  },
  {
    id: "28",
    Title: "realme 12x 5G (Twilight Purple, 128 GB)",
    Name: "realme 12x 5G (Twilight Purple, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/c/3/-original-imah3chxfqnezjjb.jpeg?q=70&crop=false",
    Actualprice: "17,999",
    Price: "12,499",
    Rating: "4.4",
    Discount: "30",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹5500 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with MobileT&CEMI starting from ₹440/monthView Plans",
    Numberofrating: "83,321 Ratings"
  },
  {
    id: "29",
    Title: "realme C63 (Leather Blue, 128 GB)",
    Name: "realme C63 (Leather Blue, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/7/s/h/-original-imah2pgrrhz2nufs.jpeg?q=70&crop=false",
    Actualprice: "10,999",
    Price: "8,999",
    Rating: "4.3",
    Discount: "18",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹500 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹2000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with MobileT&CView 1 more offer",
    Numberofrating: "6,201 Ratings"
  },
  {
    id: "30",
    Title: "realme P1 Speed 5G (Textured Titanium, 128 GB)",
    Name: "realme P1 Speed 5G (Textured Titanium, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/n/3/-original-imah5m3q8hckjpsn.jpeg?q=70&crop=false",
    Actualprice: "20,999",
    Price: "17,999",
    Rating: "4.3",
    Discount: "14",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank OfferFlat ₹1,200 off on HDFC Bank Credit Card EMI Txns on 6 and 9 months tenure, Min. Txn Value: ₹15,000T&CBank OfferFlat ₹1,500 off on HDFC Bank Credit Card EMI Txns on 12 months tenure, Min. Txn Value: ₹15,000T&CNo cost EMI ₹6,000/month. Standard EMI also availableView PlansView 8 more offers",
    Numberofrating: "711 Ratings"
  },
  {
    id: "31",
    Title: "vivo T3 5G (Crystal Flake, 128 GB)",
    Name: "vivo T3 5G (Crystal Flake, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/6/x/2/-original-imagz6tzewyqpgtz.jpeg?q=70&crop=false",
    Actualprice: "22,999",
    Price: "18,499",
    Rating: "4.4",
    Discount: "19",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹1500 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹1500 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹3,084/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "76,114 Ratings"
  },
  {
    id: "32",
    Title: "vivo V30 Pro 5G (Andaman Blue, 256 GB)",
    Name: "vivo V30 Pro 5G (Andaman Blue, 256 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/8/t/d/v30-pro-5g-v2319-vivo-original-imagyzhhdeezbbfb.jpeg?q=70&crop=false",
    Actualprice: "46,999",
    Price: "38,999",
    Rating: "4.5",
    Discount: "17",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹4000 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹2401 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹4,334/month. Standard EMI also availableView PlansView 1 more offer",
    Numberofrating: "5,034 Ratings"
  },
  {
    id: "33",
    Title: "vivo T3 Lite 5G (Vibrant Green, 128 GB)",
    Name: "vivo T3 Lite 5G (Vibrant Green, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/i/r/t3-lite-5g-v2356-vivo-original-imah27wmfgkergtx.jpeg?q=70&crop=false",
    Actualprice: "14,499",
    Price: "10,499",
    Rating: "4.4",
    Discount: "27",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹500 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹3,500/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "36,245 Ratings"
  },
  {
    id: "34",
    Title: "vivo T3x 5G (Crimson Bliss, 128 GB)",
    Name: "vivo T3x 5G (Crimson Bliss, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/3/4/-original-imahyytukhkky5ew.jpeg?q=70&crop=false",
    Actualprice: "17,499",
    Price: "12,999",
    Rating: "4.5",
    Discount: "25",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹1250 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹4500 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹4,333/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "35,589 Ratings"
  },
  {
    id: "35",
    Title: "vivo T3 Lite 5G (Vibrant Green, 128 GB)",
    Name: "vivo T3 Lite 5G (Vibrant Green, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/h/i/r/t3-lite-5g-v2356-vivo-original-imah27wmfgkergtx.jpeg?q=70&crop=false",
    Actualprice: "15,499",
    Price: "11,499",
    Rating: "4.4",
    Discount: "25",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹500 Off On All Banks Credit and Debit Card Transactions.T&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹3,833/month. Standard EMI also availableView PlansView 2 more offers",
    Numberofrating: "52,577 Ratings"
  },
  {
    id: "36",
    Title: "vivo T3x 5G (Crimson Bliss, 128 GB)",
    Name: "vivo T3x 5G (Crimson Bliss, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/3/4/-original-imahyytukhkky5ew.jpeg?q=70&crop=false",
    Actualprice: "18,999",
    Price: "14,499",
    Rating: "4.5",
    Discount: "23",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer₹1250 Off On All Banks Credit and Debit Card Transactions.T&CNo cost EMI ₹4,833/month. Standard EMI also availableView PlansExtra 10% off on Combo with MobileT&CView 1 more offer",
    Numberofrating: "95,054 Ratings"
  },
  {
    id: "37",
    Title: "POCO M6 5G (Polaris Green, 64 GB)",
    Name: "POCO M6 5G (Polaris Green, 64 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/x/x/x/-original-imah4gzvgzrkwhtg.jpeg?q=70&crop=false",
    Actualprice: "11,999",
    Price: "7,999",
    Rating: "4.2",
    Discount: "33",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - pocoT&CEMI starting from ₹282/monthView Plans",
    Numberofrating: "93,135 Ratings"
  },
  {
    id: "38",
    Title: "POCO C65 (Pastel Blue, 128 GB)",
    Name: "POCO C65 (Pastel Blue, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/u/8/c65-mzb0g8nin-poco-original-imagw6j2kp5t5jek.jpeg?q=70&crop=false",
    Actualprice: "10,999",
    Price: "6,999",
    Rating: "4.3",
    Discount: "36",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - pocoT&CEMI starting from ₹247/monthView Plans",
    Numberofrating: "84,193 Ratings"
  },
  {
    id: "39",
    Title: "POCO M6 Plus 5G (Ice Silver, 128 GB)",
    Name: "POCO M6 Plus 5G (Ice Silver, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/7/8/3/-original-imah4b2z3dsggygs.jpeg?q=70&crop=false",
    Actualprice: "17,999",
    Price: "12,499",
    Rating: "4.2",
    Discount: "30",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹5500 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹4,167/month. Standard EMI also availableView PlansExtra 10% off on Combo with Mobile - pocoT&C",
    Numberofrating: "2,562 Ratings"
  },
  {
    id: "40",
    Title: "POCO M6 5G (Galactic Black, 64 GB)",
    Name: "POCO M6 5G (Galactic Black, 64 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/t/w/0/-original-imah4gzvykvn3hbh.jpeg?q=70&crop=false",
    Actualprice: "11,999",
    Price: "7,999",
    Rating: "4.2",
    Discount: "33",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - pocoT&CEMI starting from ₹282/monthView Plans",
    Numberofrating: "93,135 Ratings"
  },
  {
    id: "41",
    Title: "POCO M6 5G (Orion Blue, 64 GB)",
    Name: "POCO M6 5G (Orion Blue, 64 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/i/2/-original-imah4gzvrgwnayrb.jpeg?q=70&crop=false",
    Actualprice: "11,999",
    Price: "7,999",
    Rating: "4.2",
    Discount: "33",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4000 off (price inclusive of cashback/coupon)T&CExtra 10% off on Combo with Mobile - pocoT&CEMI starting from ₹282/monthView Plans",
    Numberofrating: "93,135 Ratings"
  },
  {
    id: "42",
    Title: "POCO M6 Plus 5G (Misty Lavender, 128 GB)",
    Name: "POCO M6 Plus 5G (Misty Lavender, 128 GB)  (6 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/9/b/n/-original-imah3afnqj84usyy.jpeg?q=70&crop=false",
    Actualprice: "15,999",
    Price: "11,499",
    Rating: "4.2",
    Discount: "28",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CSpecial PriceGet extra ₹4500 off (price inclusive of cashback/coupon)T&CNo cost EMI ₹3,833/month. Standard EMI also availableView PlansExtra 10% off on Combo with Mobile - pocoT&C",
    Numberofrating: "14,498 Ratings"
  },
  {
    id: "43",
    Title: "Motorola g45 5G (Brilliant Blue, 128 GB)",
    Name: "Motorola g45 5G (Brilliant Blue, 128 GB)  (4 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/r/l/c/-original-imah3xk892aj9gck.jpeg?q=70&crop=false",
    Actualprice: "12,999",
    Price: "10,999",
    Rating: "4.3",
    Discount: "15",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank OfferExtra ₹500 off on DBS Bank Debit Card Transactions on orders of ₹25,000 and aboveT&CSpecial PriceGet extra ₹2000 off (price inclusive of cashback/coupon)T&CView 2 more offers",
    Numberofrating: "10,686 Ratings"
  },
  {
    id: "44",
    Title: "Motorola Edge 50 Fusion (Forest Blue, 256 GB)",
    Name: "Motorola Edge 50 Fusion (Forest Blue, 256 GB)  (12 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/w/r/edge-50-fusion-pb300000in-motorola-original-imahywzztyktktpp.jpeg?q=70&crop=false",
    Actualprice: "27,999",
    Price: "24,999",
    Rating: "4.5",
    Discount: "10",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank OfferExtra ₹500 off on DBS Bank Debit Card Transactions on orders of ₹25,000 and aboveT&CSpecial PriceGet extra ₹3000 off (price inclusive of cashback/coupon)T&CView 2 more offers",
    Numberofrating: "77,370 Ratings"
  },
  {
    id: "45",
    Title: "Motorola G85 5G (Urban Grey, 256 GB)",
    Name: "Motorola G85 5G (Urban Grey, 256 GB)  (12 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/q/f/-original-imah2fjd75hkcynr.jpeg?q=70&crop=false",
    Actualprice: "22,999",
    Price: "19,999",
    Rating: "4.4",
    Discount: "13",
    Availableoffer: "Sold OutThis item is currently out of stock",
    Numberofrating: "32,636 Ratings"
  },
  {
    id: "46",
    Title: "Motorola g45 5G (Brilliant Green, 128 GB)",
    Name: "Motorola g45 5G (Brilliant Green, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/y/x/-original-imah3xk8crpgrg9y.jpeg?q=70&crop=false",
    Actualprice: "14,999",
    Price: "12,999",
    Rating: "4.4",
    Discount: "13",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank OfferExtra ₹500 off on DBS Bank Debit Card Transactions on orders of ₹25,000 and aboveT&CSpecial PriceGet extra ₹2000 off (price inclusive of cashback/coupon)T&CView 2 more offers",
    Numberofrating: "52,118 Ratings"
  },
  {
    id: "47",
    Title: "Motorola Edge 50 Fusion (Hot Pink, 128 GB)",
    Name: "Motorola Edge 50 Fusion (Hot Pink, 128 GB)  (8 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/i/k/l/edge-50-fusion-pb300001in-motorola-original-imahywzpfd2jh9ep.jpeg?q=70&crop=false",
    Actualprice: "25,999",
    Price: "22,999",
    Rating: "4.5",
    Discount: "11",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank OfferExtra ₹500 off on DBS Bank Debit Card Transactions on orders of ₹25,000 and aboveT&CExtra 10% off on Combo with MobileT&CView 1 more offer",
    Numberofrating: "75,214 Ratings"
  },
  {
    id: "48",
    Title: "Motorola Edge 50 Fusion (Marshmallow Blue, 256 GB)",
    Name: "Motorola Edge 50 Fusion (Marshmallow Blue, 256 GB)  (12 GB RAM)",
    Image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/5/t/j/edge-50-fusion-pb300002in-motorola-original-imahywzrfagkuyxx.jpeg?q=70&crop=false",
    Actualprice: "27,999",
    Price: "24,999",
    Rating: "4.5",
    Discount: "10",
    Availableoffer: "Available offersBank Offer5% Unlimited Cashback on Flipkart Axis Bank Credit CardT&CBank Offer10% off on DBS Bank Debit Card Transactions, up to ₹1,000 on orders of ₹5,000 and aboveT&CBank OfferExtra ₹500 off on DBS Bank Debit Card Transactions on orders of ₹25,000 and aboveT&CSpecial PriceGet extra ₹3000 off (price inclusive of cashback/coupon)T&CView 2 more offers",
    Numberofrating: "77,370 Ratings"
  }
];